IMAGE_NAME = "chenhan/ubuntu-desktop-19.10"
N = 2

Vagrant.configure("2") do |config|
    

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 4
        v.gui = true
    end
      
    config.vm.define "master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "deploy.yml"
            ansible.extra_vars = {
                node_ip: "192.168.50.10",
            }
            ansible.galaxy_command = {
                galaxy_role_file = "requirements.yml"
                }
        end
    end
end