IMAGE_NAME = "Javiito32/LUbuntu"

Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
        v.gui = true
        
    end
    
    config.vm.box_version = "20.10"
    
    config.vm.define "master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "vm-deploy.yml"
            ansible.verbose = "vv"
            ansible.extra_vars = {
                node_ip: "192.168.50.10",
            }
        end
    end
end
