- name: "student"
  hosts: master 
  become_method: sudo
  become_user: root
  become: no
  vars:
    ansible_python_interpreter: python3
    ansible_become_pass: root
    ansible_pkg_mgr: apt
    eclipse_base_dir: "/home/vagrant/ide/eclipse" 
  tasks:
    - name: Include task list in play only if the condition is true
      include: "roles/tasks/main.yml"
      
    - name: change shell to zsh
      expect:
        command: "chsh -s /usr/bin/zsh"
        responses:
          (?i)password: "vagrant"
 