- name: Install sdkman 
  shell: curl -s "https://get.sdkman.io"| zsh 
  ignore_errors: yes
  become: false

- name: sdkman install java
  shell: source ~/.zshrc && sdk install java
  args:
    executable: /bin/zsh
  ignore_errors: yes
  become: false

