- name: Install microk8s
  snap:
    name:
      - microk8s
    classic: yes
    channel: latest/stable
  ignore_errors: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  become: true

- name: Install dbeaver
  snap:
    name:
      - dbeaver-ce
    classic: yes
  ignore_errors: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  become: true

- name: Install eclipse
  snap:
    name:
      - eclipse
    classic: yes
  ignore_errors: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  become: true

- name: Install ccls
  snap:
    name:
      - ccls
    classic: yes
  ignore_errors: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  become: true

- name: Install cheat
  snap:
    name:
      - cheat
    classic: yes
  ignore_errors: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  become: true

- name: Install postman
  snap:
    name:
      - postman
    classic: yes
  ignore_errors: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  become: true


- name: Install neovim 
  snap:
    name:
      - nvim
    channel: latest/edge
    classic: yes
  ignore_errors: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  become: true

