IMAGE_NAME = "peru/ubuntu-20.04-desktop-amd64"
N = 2

Vagrant.configure("2") do |config|
    

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
        v.gui = true
    end
      
    config.vm.define "master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "vm-deploy.yml"
            ansible.verbose = "vv"
            ansible.extra_vars = {
                node_ip: "192.168.50.10",
            }
        end
    end
end
